#
# ~/.modaclouds/env.sh template
#
#
instance_ids=(
	$instances
)

export FQDN=$(get_fqdn)
export NODE_PUBLIC_IP=$(get_public_address)

###
#
# Set ips and ports where each service can find other services
#

#
# MYSQL
#
export MODACLOUDS_MYSQL_ENDPOINT_IP=127.0.0.1
export MODACLOUDS_MYSQL_ENDPOINT_PORT=3306

#
# RABBITMQ
#
export MODACLOUDS_RABBITMQ_ENDPOINT_IP=$(get_addr rabbitmq)
export MODACLOUDS_RABBITMQ_ENDPOINT_PORT=21688

#
# FUSEKI T4C
#
export MODACLOUDS_FUSEKI_T4C_ENDPOINT_IP=$(get_addr fuseki-t4c)
export MODACLOUDS_FUSEKI_T4C_ENDPOINT_PORT=3030

#
# FUSEKI FG
#
export MODACLOUDS_FUSEKI_FG_ENDPOINT_IP=$(get_addr fuseki-fg)
export MODACLOUDS_FUSEKI_FG_ENDPOINT_PORT=3040

#
# OBJECT STORE
#
export MOSAIC_OBJECT_STORE_ENDPOINT_IP=$(get_addr object-store)
export MOSAIC_OBJECT_STORE_ENDPOINT_PORT=20622

#
# TOWER4CLOUDS
#
export MODACLOUDS_TOWER4CLOUDS_DATA_ANALYZER_ENDPOINT_IP=$(get_addr t4c-dda)
export MODACLOUDS_TOWER4CLOUDS_DATA_ANALYZER_ENDPOINT_PORT=8175
export MODACLOUDS_TOWER4CLOUDS_DATA_ANALYZER_ENDPOINT_IP_PUBLIC=$(get_public_addr t4c-dda)
export MODACLOUDS_TOWER4CLOUDS_DATA_ANALYZER_ENDPOINT_PORT_PUBLIC=8175

export MODACLOUDS_TOWER4CLOUDS_MANAGER_ENDPOINT_IP=$(get_addr t4c-manager)
export MODACLOUDS_TOWER4CLOUDS_MANAGER_ENDPOINT_PORT=8170
export MODACLOUDS_TOWER4CLOUDS_MANAGER_ENDPOINT_IP_PUBLIC=$(get_public_addr t4c-manager)
export MODACLOUDS_TOWER4CLOUDS_MANAGER_ENDPOINT_PORT_PUBLIC=8170

export MODACLOUDS_TOWER4CLOUDS_RDF_HISTORY_DB_ENDPOINT_IP=$(get_addr t4c-db)
export MODACLOUDS_TOWER4CLOUDS_RDF_HISTORY_DB_ENDPOINT_PORT=9100

#
# LOAD BALANCER CONTROLLER
#
export MODACLOUDS_LOAD_BALANCER_CONTROLLER_ENDPOINT_IP=0.0.0.0
export MODACLOUDS_LOAD_BALANCER_CONTROLLER_ENDPOINT_PORT=8088

#
# LOAD BALANCER REASONER
#

#
# MODELS@RUNTIME
#
export MODACLOUDS_MODELS_AT_RUNTIME_ENDPOINT_IP=$(get_addr mrt)
export MODACLOUDS_MODELS_AT_RUNTIME_ENDPOINT_PORT=9000
export MODACLOUDS_MODELS_AT_RUNTIME_ENDPOINT_IP_PUBLIC=$(get_public_addr mrt)
export MODACLOUDS_MODELS_AT_RUNTIME_ENDPOINT_PORT_PUBLIC=9000

#
# SLA
#
export MODACLOUDS_SLACORE_ENDPOINT_IP=$(get_addr sla)
export MODACLOUDS_SLACORE_ENDPOINT_PORT=9040

