#
# ~/.modaclouds/env.sh template
#
#
instance_ids=(
	$instances
)

export FQDN=$(get_fqdn)
export NODE_PUBLIC_IP=$(get_public_address)

###
#
# Set ips and ports where each service can find other services
#

#
# MYSQL
#
export MODACLOUDS_MYSQL_ENDPOINT_IP=127.0.0.1
export MODACLOUDS_MYSQL_ENDPOINT_PORT=3306

#
# RABBITMQ
#
export MODACLOUDS_RABBITMQ_ENDPOINT_IP=$(get_addr rabbitmq)
export MODACLOUDS_RABBITMQ_ENDPOINT_IP_HACK=$(get_public_addr rabbitmq)
export MODACLOUDS_RABBITMQ_ENDPOINT_PORT=21688

#
# FUSEKI (one instance to rule them all)
#
export MODACLOUDS_FUSEKI_ENDPOINT_IP=$(get_addr fuseki)
export MODACLOUDS_FUSEKI_ENDPOINT_IP_HACK=$(get_public_addr fuseki)
export MODACLOUDS_FUSEKI_ENDPOINT_PORT=3030

#
# OBJECT STORE
#
export MOSAIC_OBJECT_STORE_ENDPOINT_IP=$(get_addr object-store)
export MOSAIC_OBJECT_STORE_ENDPOINT_PORT=20622

#
# TOWER4CLOUDS
#
export MODACLOUDS_TOWER4CLOUDS_DATA_ANALYZER_ENDPOINT_IP=$(get_addr t4c-dda)
export MODACLOUDS_TOWER4CLOUDS_DATA_ANALYZER_ENDPOINT_PORT=8175
export MODACLOUDS_TOWER4CLOUDS_DATA_ANALYZER_ENDPOINT_IP_PUBLIC=$(get_public_addr t4c-dda)
export MODACLOUDS_TOWER4CLOUDS_DATA_ANALYZER_ENDPOINT_PORT_PUBLIC=8175

export MODACLOUDS_TOWER4CLOUDS_MANAGER_ENDPOINT_IP=$(get_addr t4c-manager)
export MODACLOUDS_TOWER4CLOUDS_MANAGER_ENDPOINT_PORT=8170
export MODACLOUDS_TOWER4CLOUDS_MANAGER_ENDPOINT_IP_PUBLIC=$(get_public_addr t4c-manager)
export MODACLOUDS_TOWER4CLOUDS_MANAGER_ENDPOINT_PORT_PUBLIC=8170

export MODACLOUDS_TOWER4CLOUDS_RDF_HISTORY_DB_ENDPOINT_IP=$(get_addr t4c-db)
export MODACLOUDS_TOWER4CLOUDS_RDF_HISTORY_DB_ENDPOINT_PORT=9100

#
# LOAD BALANCER CONTROLLER
#
export MODACLOUDS_LOAD_BALANCER_CONTROLLER_ENDPOINT_IP=$(get_addr lb-controller)
export MODACLOUDS_LOAD_BALANCER_CONTROLLER_ENDPOINT_PORT=8088

#
# LOAD BALANCER REASONER (doesn't provide endpoint)
#

#
# MODELS@RUNTIME
#
export MODACLOUDS_MODELS_AT_RUNTIME_ENDPOINT_IP=$(get_addr mrt)
export MODACLOUDS_MODELS_AT_RUNTIME_ENDPOINT_PORT=9000
export MODACLOUDS_MODELS_AT_RUNTIME_ENDPOINT_IP_PUBLIC=$(get_public_addr mrt)
export MODACLOUDS_MODELS_AT_RUNTIME_ENDPOINT_PORT_PUBLIC=9000

#
# SLA
#
export MODACLOUDS_SLACORE_ENDPOINT_IP=$(get_addr sla)
export MODACLOUDS_SLACORE_ENDPOINT_PORT=9040

#
# FG LOCAL DB (doesn't provide endpoint)
#
# Vars above not needed when package updated
export MODACLOUDS_FG_LOCAL_DB_COLLECTION="/v1/collections/FG/objects/"
export MODACLOUDS_FG_LOCAL_DB_CONFIG_OBJECT="fg_metrics/data"

#
# FG ANALYZER (doesn't provide endpoint)
#
# Vars above not needed when package updated
export MODACLOUDS_FG_ANALYZER_COLLECTION="/v1/collections/FG/objects/"
export MODACLOUDS_FG_ANALYZER_CONFIG_OBJECT="config/data"

#
# METRIC EXPLORER
#
export MODACLOUDS_METRIC_EXPLORER_QUERY_ENDPOINT_IP=$(get_addr metric-explorer)
export MODACLOUDS_METRIC_EXPLORER_QUERY_ENDPOINT_PORT=9011
export MODACLOUDS_METRIC_EXPLORER_PICKLE_RECEIVER_ENDPOINT_IP=$(get_addr metric-explorer)
export MODACLOUDS_METRIC_EXPLORER_PICKLE_RECEIVER_ENDPOINT_PORT=9012
export MODACLOUDS_METRIC_EXPLORER_LINE_RECEIVER_ENDPOINT_IP=$(get_addr metric-explorer)
export MODACLOUDS_METRIC_EXPLORER_LINE_RECEIVER_ENDPOINT_PORT=9013
export MODACLOUDS_METRIC_EXPLORER_DASHBOARD_ENDPOINT_IP=$(get_addr metric-explorer)
export MODACLOUDS_METRIC_EXPLORER_DASHBOARD_ENDPOINT_PORT=9010
